name: My First Workflow
on:
  push:
    branches: 
      - main
  workflow_dispatch:  
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo '👋 Hello Github'
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
