name: Needs Test
on:
  push:
    branches: 
      - main
  workflow_dispatch:
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'running job_1'
  job_2:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'running job_2'
    needs: [job_1]
  job_3:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'running job_3'
    needs: [job_1]
  job_4:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'running job_4'
    needs: [job_2, job_3]
